electron/roller

src/pr.ts

Currently, Roller generates PRs in https://github.com/electron/electron reading https://github.com/electron/libchromiumcontent commits, so the issue/pr references are broken.
e.g., https://github.com/electron/electron/pull/14214
> 7e5528dd Fix Chromium tests compilation with Electron patches (#655)
This PR makes the issue/pr references to link them to libchromiumcontent's issue/pr.

fix: correct pr/issue references.

---

src/roll-chromium.ts

causes error:
```
roller:handleChromiumCheck() Error rolling 6-0-x to 76.0.3796.1 TypeError: Cannot read property '1' of null
at Object.rollChromium4 (/app/lib/roll-chromium.js:164:102)
at process._tickCallback (internal/process/next_tick.js:68:7) +1s
```

fix: version matching regex

---

.gitignore

Our `npm test` command currently auto-generates a `/coverage/` report from Jest.

chore: add jest coverage folder to gitignore

---

src/utils/octokit.ts

Noticed this warning when running stuff locally.
```
[@octokit/rest] octokit.authenticate() is deprecated. Use "auth" constructor option instead.'
```
See code: https://github.com/octokit/rest.js/blob/7601bd78c449bf33c2058ce94e2ef3e7d3106c9c/plugins/authentication-deprecated/authenticate.js#L8-L10
Updated the call to reflect the Octokit docs: https://octokit.github.io/rest.js/#authentication

chore: update deprecated call to authenticate

---

src/roll-chromium.ts

There should be no effect because `REPO_OWNER` and `REPO_NAME` are the same for `electron/electron`, but we should be using `REPO_OWNER` in the business logic here.
[See GitHub docs for the `head` attribute](https://developer.github.com/v3/pulls/#input):
>The name of the branch where your changes are implemented. For cross-repository pull requests in the same network, namespace head with a user like this: `username:branch`.

fix: correct constant in roll Chromium PR request

---

src/roll-chromium.ts

This PR updates the link `See [all changes in See all changes in xx.x.xxxx.xx..yy.y.yyyy.yy]` to use the more descriptive format that shows logs as well as the file changes, eg: 
https://chromium.googlesource.com/chromium/src/+log/76.0.3809.74..76.0.3809.77?n=10000&pretty=fuller
instead of 
https://chromium.googlesource.com/chromium/src/+/76.0.3809.74..76.0.3809.77

feat: use more descriptive link to view changes

---

src/roll-chromium.ts

The thought here is that if a PR is taking more than 10 days to land we should probably stop adding new breakage to the PR and let maintainers fix what's there.

feat: stop bumping PRs after 10 days [RFC]

---

src/utils/roll.ts
tests/utils/pr-text-spec.ts
tests/utils/roll-spec.ts

Update `roller` to halt updates in a label rather than time-delimited fashion
Adding the `pause-roll` label to a PR will prevent DEPS updates.
cc @electron/wg-upgrades

feat: pause updates on label not time

---

package.json

Updates npm scripts to make local runs more accurate and simpler. Also remove unnecessary `npm start`.
cc @nornagon @MarshallOfSound

chore: update npm scripts and remove start

---

.github/CODEOWNERS

Set @electron/wg-upgrades as a CODEOWNER for roller.
cc @electron/wg-upgrades

chore: add upgrades as CODEOWNERS

---

package.json
src/handlers.ts
src/utils/roll.ts
tests/handlers-spec.ts

Heroku does seem to expect a `start` script even if it's a no-op, so i've gone ahead and added that back. Also cleans up and adds some more verbose logging.
cc @MarshallOfSound @nornagon

chore: improve logging and add start

---

src/constants.ts
src/handlers.ts
src/utils/update-deps.ts
tests/handlers-spec.ts
tsconfig.json

Ensures that only applicable supported branches are rolled against. At present, for example, only `8-x-y`, `7-1-x`, `6-1-x`, and `5-0-x` would need to be rolled against. This also allows us to remove code that checks against versions being rolled against that are <= v3.
Also changes the octokit call in `handleNodeCheck` from `listBranches` to `getBranch` since we're only rolling `master` for now.
cc @nornagon @jkleinsc

fix: properly check for supported branches

---

src/utils/roll.ts
tests/utils/roll-spec.ts

Closes https://github.com/electron/roller/issues/41.
Checks if a valid ref already exists (but no PR is open, meaning that it's an orphan branch) and deletes the ref before attempting to open a new roller PR.
cc @erickzhao @nornagon

fix: delete orphan branches before rolling

---

src/utils/roll.ts

Fixes a bug in the GitHub API whereby nonexistent refs are _supposed_ to return a status 404, but instead throw an HTTP error. 
Prior art taken from the approach of a GitHub employee who worked around this issue the same way in [this action](https://github.com/jeffrafter/setup-action/blob/0d86e4ae9bfea76f2cb733208310277fb6e29b8e/setup.ts#L26-L39)
cc @nornagon

fix: httperror on ref not found

---

src/handlers.ts
src/utils/get-chromium-tags.ts
src/utils/pr-text.ts
tests/handlers-spec.ts
tests/utils/pr-text-spec.ts

LGKR is not reliably updated anymore - we should roll on `master` instead to avoid ending up behind. We may end up needing to revert this depending on how bad commits filter down to us, but we'll see and iterate.
cc @nornagon

refactor: roll on Chromium master not lkgr

---

src/handlers.ts
tests/handlers-spec.ts

This PR updates roller to work with our 10-x-y branch.

fix: update supported branch pattern for 2 digit versions

---

src/handlers.ts
src/utils/get-chromium-tags.ts
tests/handlers-spec.ts

Switch from using chromium's available tags to using [OmahaProxy](https://omahaproxy.appspot.com/) data for determining which Chromium versions to roll into Electron.
This will hopefully help us avoid issues like https://github.com/electron/electron/pull/25499 in the future.

fix: use omahaproxy release data

---

src/utils/get-chromium-tags.ts

omahaproxy doesn't put the `]})` nonsense in front of its JSON.

fix: parsing of omahaproxy json

---

src/handlers.ts

Older versions of chrome don't show up in the omahaproxy release history, so
check for null.

fix: check null release

---

src/handlers.ts

Tiny change - we should log when no upgrade is possible for Node.js to 
1) match behavior for Chrome roll logic
2) make parsing logs easier
cc @nornagon @MarshallOfSound

chore: log when no upgrade possible

---

src/handlers.ts
src/utils/get-chromium-tags.ts
tests/handlers-spec.ts

As discussed in upgrades-wg this morning, this is backwards compatible so on merge the next roll commit will move us to a version number

chore: roll master to chromium version instead of SHA

---

src/utils/roll.ts
tests/handlers-spec.ts
tests/utils/roll-spec.ts

This gets roller green again.
* lint: ran `prettier:write`
* roll-spec: sync to e2e9b2a3d5b63f80d3497821f2744fb8f798428e
* handlers-spec: sync to 81e60c450ccd4e1c0e512029cdfaf2c9bdac1a50

fix: 'test' and 'lint' are both failing

---

app.json
package.json
src/handlers.ts
src/utils/octokit.ts
src/utils/roll.ts
src/utils/update-deps.ts
tsconfig.json
yarn.lock

Currently we use `GITHUB_TOKEN` which is a super-token generated by an account with a little bit _too much_ permission.  Let's switch to using a GH app with much more scoped permissions

refactor: use github app instead of super token

---

src/utils/roll.ts

Saw this here https://github.com/electron/electron/pull/29321
We should add the `backport-check-skip` label so trop doesn't hell at roller.

fix: disable trop backport checks for PRs to older branches

---

src/constants.ts
src/utils/roll.ts
tests/utils/roll-spec.ts

`main` PRs should have the `no-backport` label applied, and release branches should have the `backport-check-skip` label applied.
Other small changes 
* We don't need `PR_USER` as a constant 
* We should test that trop PRs don't trigger any action
* Prettier on test files

fix: backport labels for branches

---

tests/handlers-spec.ts

Fixes failure borne of missing jest mock for `octokit.repos.getBranch`

test: fix missing jest mock

---

src/handlers.ts
src/utils/get-chromium-tags.ts
tests/handlers-spec.ts

This will hopefully get us Extended Stable data, which omahaproxy lacks.

fix: use chromiumdash instead of omahaproxy for release data

---

src/utils/octokit.ts

Spotted this while looking at the code today trying to figure out why https://github.com/electron/electron/pull/40484 got closed.
Looks like `getAppOctokit()` is an unused method, so this PR removes it

refactor: remove unused method getAppOctokit()

---

src/orb-handler.ts
src/utils/roll-orb.ts

some node orb repos may not have a valid release, but have tags. This PR adds a backup code path that should get a list of repository tags, filter the ones that are semver compliant and get the latest satisfying tag.

chore: check for latest tag if latest release cannot be found

---

src/utils/roll-orb.ts

When rolling an orb with an existing PR, await this promise, otherwise errors won't be properly handled if the content cannot be updated.

fix: await promise

---

src/utils/roll-orb.ts
tests/utils/roll-orb-spec.ts

Reverts #101. I believe the underlying issue was misunderstood in that change - the error was because the CircleCI config content was being fetched from the ref, so if it hadn't been created, that would fail. In the case of no PR existing, just get the config content from the default branch, and then determine if the roll needs to continue, creating the ref at that point.

chore: lazily create ref when rolling orb

---

src/node-handler.ts
src/utils/get-nodejs-lts.ts
tests/handlers-spec.ts

Follow up to https://github.com/electron/roller/pull/111
Use https://github.com/nodejs/Release/blob/main/schedule.json to determine current active LTS, and allow rolling to a new major version once it becomes active LTS.

fix: scope main roll to active LTS

---

src/utils/label-utils.ts
src/utils/octokit.ts
src/utils/roll.ts
tests/utils/roll-spec.ts

Tie-in work to roll Node.js more regularly in existing release lines. Unlike Chromium, we can distinguish between patch and minor bumps in Chromium, and adjust the semver label accordingly.

fix: correctly label Node.js version bump semver

---

src/utils/roll.ts

Fixes missing `backport-check-skip` label being applied to Node.js release branch rolls
Example: https://github.com/electron/electron/pull/42613
this was happening because `labelsToAdd` was being overwritten when the target was Node.js, clobbering the initial skip label.

fix: backport-check-skip applied to Node.js release branch PRs

---

.github/workflows/test.yml

Also schedules CI to run on a regular schedule so we can spot failures sooner (or in this case the deprecation warning). This is now standard practice on our repos.

ci: bump actions/cache to non-deprecated version

---

src/utils/octokit.ts

The current implementation is getting an installation auth token and then holding on to it indefinitely, which is a problem because those expire after 60 minutes. Refactor to use the proper approach to let Octokit fetch new tokens as needed.

fix: don't hold on to raw auth tokens

---

.gitignore
src/constants.ts
src/utils/arc-image.ts
src/utils/pr-text.ts
src/utils/roll-infra.ts
src/windows-image-cron.ts
src/windows-image-handler.ts

Avoids issues like we saw today where the windows ARC image drifted from what was "last" on main.
This logic is a bit fiddly but basically, we'll update the image SHA if:
* The sha of the latest `main` image is different to the current image
* The difference between the `Dockerfile` for "current" and "end" is non-empty (i.e. the windows dockerfile was actually updated)

build: roll windows arc images automatically

---

src/actions-runner-cron.ts
src/actions-runner-handler.ts
src/constants.ts
src/utils/arc-image.ts
src/utils/get-latest-runner-images.ts
tests/actions-runner-handler.test.ts
tests/utils/arc-image.test.ts
tests/utils/get-latest-runner-images.test.ts

This PR adds roll capability to our github actions runner images.  If a new version is available at https://github.com/actions/runner/pkgs/container/actions-runner, create a PR updating the infra repo with the new runner version.

build: roll github actions runners automatically

---

src/actions-runner-handler.ts
src/utils/arc-image.ts
src/utils/get-latest-runner-images.ts
tests/actions-runner-handler.test.ts
tests/utils/arc-image.test.ts
tests/utils/get-latest-runner-images.test.ts

- Followup to #147.
When the GitHub Actions runner roller ran, it accidentally tried to update the linux containers as follows:
FROM:
```
image: ghcr.io/actions/actions-runner:2.325.0@sha256:b865e3f046f0a92a4b936ae75c5bc5615b99b64eb4801b0e5220f13f8867d6b8
```
TO:
```
image: sha256:b865e3f046f0a92a4b936ae75c5bc5615b99b64eb4801b0e5220f13f8867d6b8 
```
This PR fixes that issue and also updates the tests to better verify the GitHub Actions roller.

fix: github actions runner roller for linux

---

.github/workflows/test.yml
tsconfig.json

- Fixes the following error introduced in #148
```
src/actions-runner-handler.ts(49,39): error TS2550: Property 'replaceAll' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2021' or later.
```

build: update ts target to es2021 to get string.replaceAll

---

src/utils/arc-image.ts
src/windows-image-handler.ts
tests/utils/arc-image.test.ts

Needed as a followup to https://github.com/electron/electron/pull/47897.

chore: update windows-image-roller for new arc cluster
