electron/roller

src/chromium-cron.ts
src/get-chromium-tags.ts
src/handlers.ts
src/index.ts
src/pr.ts
src/roll-chromium.ts

> the code speaks for itself
@nornagon 2k19

feat: handle bumping chromium

---

.circleci/config.yml
.travis.yml

This moves our CI config to CircleCI

build: move to circleci

---

src/constants.ts
src/pr.ts
src/roll-chromium.ts
tests/roll-chromium-spec.ts

Does what it says on the tin, need to update the GITHUB_TOKEN on heroku once merged

feat: make PRs on the electron repo itself

---

.gitignore
package.json
src/get-extra-commits.ts
src/handlers.ts
src/index.ts
src/pr.ts
src/roll-chromium.ts
tests/handlers-spec.ts
tests/mocks/octokit.ts
tests/roll-chromium-spec.ts

What it says on the tin.
cc @nornagon @MarshallOfSound

chore: update octokit

---

src/handlers.ts

this branch appears abandoned upstream.

fix: ignore 78.0.3905

---

src/handlers.ts
src/utils/octokit.ts
src/utils/roll.ts
src/utils/update-deps.ts

the function didn't do anything asynchronous, so no need for it to be async.

refactor: getOctokit is synchronous

---

src/utils/roll.ts

Closes https://github.com/electron/roller/issues/58.
See: https://papertrailapp.com/systems/electron-roller/events?focus=1291070800246308872

feat: allow updating human-opened PRs

---

src/utils/roll.ts

Addresses an outstanding todo.

chore: cleanup older Chromium roll cruft

---

.husky/pre-commit
package.json
yarn.lock

Correct lint issues when staging files for commit.

build: lint on commit

---

src/handlers.ts
src/utils/pr-text.ts
tests/handlers-spec.ts
tests/utils/pr-text-spec.ts

Attempts rolls on both `main` and `master` for chromium and node.

feat: support main branch

---

.circleci/config.yml
jest.json
package.json
yarn.lock

As in title, no user facing changes

build: update deps to clean up yarn audit

---

src/index.ts

it's nice to be able to force a roll sometimes

feat: add /roll command

---

README.md

Added two extra steps for beginners so they will not get confused.

docs: add extra installation steps

---

package.json

These were in the wrong section.

build: move deps to devDependencies

---

src/utils/roll.ts

fix: wait for deleteRef to actually work

---

src/utils/roll-orb.ts

The ref creation was moved in a commit within the previous PR (#98 ) to accomodate for not creating a ref if we don't need to update the config file. However this caused a bug when a PR had not yet been created and we needed to update the config, but didn't have the ref yet.  Adding a deleteRef should fix this

chore: fix uncreated ref

---

src/utils/roll-orb.ts

Follow-up to #105, somehow managed to duplicate the code block I moved rather than move it. 🤦 Cleaning up the original lines.

chore: remove duplicate code

---

src/node-handler.ts
tests/handlers-spec.ts

feat: auto-roll release branches node tags

---

src/chromium-handler.ts
src/index.ts
src/node-handler.ts

Match https://github.com/electron/roller/pull/91 now that our Node.js roll policy has changed.

feat: enable branch-specific rolling for Node.js

---

package.json
yarn.lock

build: remove unused @types/body-parser devDep

---

package.json
yarn.lock

Bumping this for some housekeeping - looks to work fine with no changes.

chore: upgrade to probot 13

---

src/chromium-handler.ts
src/utils/get-chromium-tags.ts
tests/handlers.spec.ts

Closes https://github.com/electron/roller/issues/131.
Scopes down fetched Chromium releases to improve fetch time.

refactor: scope Chromium releases in fetch

---

src/constants.ts

- Needed as a followup to https://github.com/electron/electron/pull/47897.

chore: update for new arc setup
